[package]
name = "testwasmtime"
version = "0.1.0"
edition = "2021"

[dependencies]
wasmtime = "25.0.1"
wasi-common = "25.0.1"
anyhow = "1.0.89"
wasmtime-wasi = "25.0.1"
tokio = { version = "1.40.0", features = ["full"] }
bytemuck = "1.18.0"
